### ISSUE TITLE
Multi-face dataset used in the paper

### ISSUE THREAD

**Issue by weijielyu** [syntec-research/Cafca#3]
Hi, thanks for this great work! I have a question about your evaluation dataset. In the paper, you use 9 subjects from the Multi-face dataset; I wonder if you can provide which subjects you used and which images you used for training and testing?

Thank you!

**Comment by mcbuehler** [comment]
We use the following subset for the comparisons with related works on [Multiface](https://github.com/facebookresearch/multiface):

**Subject 002539136**
Input cameras: 400009,400026,400053
Eval cameras: 400027,400017,400063,400048,400061,400029,400069,400007,400019,400031,400013,400059,400030,400018,400016,400042,400037,400023,400050,400028,400049,400015,400004,400041,400060,400012,400039,400064,400002,400051
E006_Jaw_Drop_Brows_Up, frame 011892
E009_Smile_Mouth_Open, frame 013211
E061_Lips_Puffed, frame 030674

**Subject 002757580**
Input cameras: 400009,400023,400042
Eval cameras: 400002,400004,400006,400007,400012,400013,400014,400016,400019,400024,400026,400027,400028,400029,400030,400031,400037,400039,400041,400048,400049,400051,400053,400059,400060,400061,400063,400064,400069
E042_Mouth_Nose_Left_C05, frame 028721
GAZ_G2_Wide_eyes_Full-led_1, frame 097793
GAZ_G3_Squint_Partial-led_12, frame 118849

**Subject 7889059**
Input cameras: 400009,400053,400059
Eval cameras: 400002,400004,400007,400012,400013,400015,400016,400017,400018,400019,400023,400026,400027,400029,400030,400031,400037,400039,400041,400042,400048,400049,400061,400063,400064,400069
E010_Smile_Stretched, frame 003814
Raise_Cheeks, frame 006385
E019_Frown, frame 006742

All comparisons are on the full-resolution images (1334 x 2048 pixels).

**Comment by weijielyu** [comment]
Thanks for the information!
