### ISSUE TITLE
Dataset structure issue

### ISSUE THREAD

**Issue by Edisoneh** [syntec-research/Cafca#4]
Hello, what a great job, especially this dataset. But I have some doubts, as mentioned in Dataset.md, dataset is structured as follows:SUBJECT/EXP_ENV, my understanding is that for the same EXP there should be the same expression with different backgrounds. But I found in the downloaded data that there seemed to be different expressions and different backgrounds. For example: 00000/00001_000 - 00000/00001_001 -00000/ 00001_002
![res](https://github.com/user-attachments/assets/b0d5f784-11a6-4e42-bd85-e3d69e55b8fc)
Are there some problems?

**Comment by mcbuehler** [comment]
Hi, the expressions (00001...00012) are sampled randomly for each environment, i.e., they are not consistent across different environments. Only the neutral expression (00000) is fixed for all samples.

I updated the documentation.

**Comment by Edisoneh** [comment]
> Hi, the expressions (00001...00012) are sampled randomly for each environment, i.e., they are not consistent across different environments. Only the neutral expression (00000) is fixed for all samples.
> 
> I updated the documentation.

I got it, thanks.
